# Generated by Django 2.2.10 on 2020-12-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0006_templatetranslation_country"),
    ]

    operations = [
        migrations.AlterField(model_name="templatetranslation", name="content", field=models.TextField()),
    ]
