# Generated by Django 2.2.20 on 2021-06-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0071_orgactivity_plan_active_contact_count"),
        ("schedules", "0013_fix_none_days"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                condition=models.Q(is_active=True, next_fire__isnull=False),
                fields=["next_fire"],
                name="schedules_next_fire_active",
            ),
        ),
    ]
