# Generated by Django 2.2.4 on 2020-04-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0058_auto_20190723_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='brand',
            field=models.CharField(default='engage', help_text='The brand used in emails', max_length=128, verbose_name='Brand'),
        ),
    ]
