# Generated by Django 2.2.4 on 2022-01-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0059_auto_20200403_1519'),
        ('orgs', '0087_auto_20210621_1642'),
    ]

    operations = [
    ]
