# Generated by Django 3.2.7 on 2021-09-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_auto_20190703_2309"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebHookResult",
        ),
    ]
