dist:
  - trusty

sudo:
  - false

addons:
  apt:
    packages:
      - postgresql-9.4-postgis-2.3
  postgresql: "9.4"

cache:
  directories:
    - "$HOME/.cache/pip"

language: python

python: 
  - "2.7.11"
  - "3.6"

services:
- redis-server

env:
  - TEST=lint
  - TEST=build

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.6"
      env: TEST=build

install:
- pip install --upgrade pip
- pip --version
- pip install -r pip-freeze.txt --upgrade
- pip install setuptools==33.1.1  # Recent version breaks packaging.requirements, this is a temp fix: https://github.com/pypa/setuptools/issues/942
- pip install coveralls
- nvm install 6
- nvm use 6
- npm install

before_script:
- psql -U postgres -c "CREATE USER temba WITH PASSWORD 'temba';"
- psql -U postgres -c "ALTER ROLE temba WITH SUPERUSER;"
- psql -d 'template1' -U postgres -c "CREATE EXTENSION postgis;"
- psql -d 'template1' -U postgres -c "CREATE EXTENSION postgis_topology;"
- psql -d 'template1' -U postgres -c "CREATE EXTENSION hstore;"
- psql -U temba postgres -c "CREATE DATABASE temba;"
- ln -s $TRAVIS_BUILD_DIR/temba/settings.py.dev $TRAVIS_BUILD_DIR/temba/settings.py

script: ./travis.sh

after_success:
- coveralls --rcfile .coveragerc_failcheck
- coverage report -i --rcfile .coveragerc
- coverage report -i --rcfile .coveragerc_failcheck --fail-under=100

notifications:
  slack:
    secure: "b2/RUpO6gWEDgOI/sEWsjt2cVnwp3hOWUSMnHpVuY0pZBzzrICZ5MeqEulwCoKy+8ohaCmYUL42RzJwq1v2FITo5YDeiLrqmrkYR0Zieel/Vey+o6sBdR6y2yPvWjBmydHNvfUyMshT5iqEn4bS6bjhm57F0rLJX7mTqp19A+68="
