# configuration related dependencies taken from pip-add-reqs.txt
[tool.poetry.custom]
amqp = "2.1.4"
dicttoxml = "1.7.4"
django-getenv = "1.3.1"
django-cache-url = "1.3.1"
uwsgi = "2.0.18"
whitenoise = "4.0"
flower = "0.9.2"
tornado = "6.0"