version: '2'
services:
  rapidpro:
    image: rapidpro/rapidpro:master
    depends_on:
      - redis
      - postgresql
    ports:
      - '8000:8000'
    environment:
      - DOMAIN_NAME=localhost
      - ALLOWED_HOSTS=localhost
      - TEMBA_HOST=localhost
      - DJANGO_DEBUG=off
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=super-secret-key
      - MANAGEPY_COLLECTSTATIC=on
      - MANAGEPY_COMPRESS=on
      - MANAGEPY_INIT_DB=on
      - MANAGEPY_MIGRATE=on
    volumes:
      - ./env:/rapidpro/env
      - ./temba/flow:/rapidpro/temba/flow
      - ./static:/rapidpro/static
      - ./templates:/rapidpro/templates
      - ./temba/settings_common.py:/rapidpro/temba/settings_common.py
  celery:
    image: rapidpro/rapidpro:master
    depends_on:
      - rapidpro
    links:
      - redis
      - postgresql
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=super-secret-key
    command: ["/rapidpro/env/bin/celery", "--beat", "--app=temba", "worker", "--loglevel=INFO", "--queues=celery,msgs,flows,handler"]
    volumes:
      - ./env:/rapidpro/env
      - ./temba/flow:/rapidpro/temba/flow
      - ./static:/rapidpro/static
      - ./templates:/rapidpro/templates
      - ./temba/settings_common.py:/rapidpro/temba/settings_common.py
  redis:
    image: redis:alpine
  postgresql:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_DB=rapidpro
    volumes:
      - rapidpro:/var/lib/postgresql/data
  mage:
   image: rapidpro/mage
   depends_on:
     - rapidpro
   links:
     - redis
     - postgresql
   environment:
     - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
     - REDIS_URL=redis://redis/
     - REDIS_DATABASE=8

volumes:
  rapidpro: