# Generated by Django 2.2.4 on 2020-05-11 21:08

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0034_add_fire_unique_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignevent',
            name='message',
            field=temba.utils.models.TranslatableField(max_length=4096, null=True),
        ),
    ]
