# Generated by Django 2.2.4 on 2020-07-01 17:56

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0034_auto_20200511_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignevent',
            name='message',
            field=temba.utils.models.TranslatableField(max_length=640, null=True),
        ),
    ]
