# Generated by Django 2.2.4 on 2022-01-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0039_auto_20210709_1912'),
        ('campaigns', '0034_add_fire_unique_index'),
    ]

    operations = [
    ]
