version: 2

jobs:
  build-containers:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Avoid "Are you sure you want to connect?" to GitHub
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            chmod 600 ~/.ssh/known_hosts
      - setup_remote_docker:
          version: 20.10.7
          # Base GEOS image cannot build, force ver 20.10.7: https://discuss.circleci.com/t/unable-to-use-make/40552/4
      - run:
          name: Login to Docker
          command: |
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      - run:
          name: Ensure GEOS Libs Image Exists, building if necessary
          command: |
            source scm/utils-engage.sh; EnsureGeosImage
      - run:
          name: Ensure Python Libs Image Exists, building if necessary
          command: |
            source scm/utils-engage.sh; EnsurePyLibsImage
      - run:
          name: Figure out tag to use
          command: |
            BRANCH=${CIRCLE_BRANCH#*/}
            VERSION_STR=$(cat VERSION)
            if [[ ! -z $CIRCLE_TAG ]]; then
              if [[ $CIRCLE_TAG == "deploy2dev" ]]; then
                VERSION_TAG="ci-${VERSION_STR}-${BRANCH}"
              else
                VERSION_TAG="${VERSION_STR}"
              fi
            elif [[ "$BRANCH" == "develop" ]]; then
              VERSION_TAG="${VERSION_STR}-dev"
            else
              VERSION_TAG="ci-${VERSION_STR}-${BRANCH}"
            fi
            echo ${VERSION_TAG} > scm/version_tag.txt
      - run:
          name: Ensure RpApp Image Exists, building if necessary
          command: |
            VERSION_TAG=$(cat scm/version_tag.txt)
            source scm/utils-engage.sh; EnsureRpAppImage default "$VERSION_TAG"
      - run:
          name: Build "Default Branding" Image
          command: |
            VERSION_TAG=$(cat scm/version_tag.txt)
            source scm/utils-engage.sh; BuildVersionForRp "$VERSION_TAG"
      - run:
          name: Build "Engage Branding" Image
          command: |
            BRANCH=${CIRCLE_BRANCH#*/}
            VERSION_TAG=$(cat scm/version_tag.txt)
            source scm/utils-engage.sh; BuildVersionForEngage "$VERSION_TAG"
            if [[ $BRANCH == develop ]]; then
              IMAGE_NAME=istresearch/p4-engage
              IMAGE_TAG=ci-develop
              docker tag ${IMAGE_NAME}:${VERSION_TAG} ${IMAGE_NAME}:${IMAGE_TAG}
              docker push ${IMAGE_NAME}:${IMAGE_TAG}
            fi
      - run:
          name: Build "Generic Branding" Image
          command: |
            VERSION_TAG=$(cat scm/version_tag.txt)
            source scm/utils-engage.sh; BuildVersionForGeneric "${VERSION_TAG}-generic"

  deploy-dev-container:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Avoid "Are you sure you want to connect?" to GitHub
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            chmod 600 ~/.ssh/known_hosts
      - run:
          name: Figure out tag to use
          command: |
            BRANCH=${CIRCLE_BRANCH#*/}
            VERSION_STR=$(cat VERSION)
            if [[ ! -z $CIRCLE_TAG ]]; then
              if [[ $CIRCLE_TAG == "deploy2dev" ]]; then
                VERSION_TAG="ci-${VERSION_STR}-${BRANCH}"
              else
                VERSION_TAG="${VERSION_STR}"
              fi
            elif [[ "$BRANCH" == "develop" ]]; then
              VERSION_TAG="${VERSION_STR}-dev"
            else
              VERSION_TAG="ci-${VERSION_STR}-${BRANCH}"
            fi
            echo ${VERSION_TAG} > scm/version_tag.txt
      - run:
          name: Deploy To K8s
          command: |
            VERSION_TAG=$(cat scm/version_tag.txt)
            K8_URL=https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/p4-deploy/tree/develop
            curl -XPOST --user "${oCI_API_TOKEN}:" \
              --data build_parameters[CIRCLE_JOB]=eks_deploy \
              --data build_parameters[DEPLOY_PROJECT]=pulse-engage \
              --data build_parameters[DEPLOY_IMAGE]=$CIRCLE_PROJECT_USERNAME/p4-engage:${VERSION_TAG} \
              $K8_URL          

workflows:
  version: 2
  pipeline:
    jobs:
      - build-containers:
          context: globalconfig
          filters:
            tags:
              ignore: /^test-.*/
      - deploy-dev-container:
          context: globalconfig
          requires:
            - build-containers
          filters:
            branches:
              only:
                - /^develop$/
                - /^dev-.*/
                - /^upstream_dev__merge$/
            tags:
              only:
                - /^deploy2dev$/
                # until we also get branch name, this tag seems 'useless'.
                
