version: 2

jobs:
  build-containers:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Avoid "Are you sure you want to connect?" to GitHub
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            chmod 600 ~/.ssh/known_hosts
      - setup_remote_docker:
          version: 20.10.8
          # Base GEOS image cannot build, force ver 20.10.7: https://discuss.circleci.com/t/unable-to-use-make/40552/4
      - run:
          name: Login to Docker
          command: |
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      - run:
          name: Ensure GEOS Libs Image Exists, building if necessary
          command: |
            source scm/utils-engage.sh; EnsureGeosImage
      - run:
          name: Ensure Python Libs Image Exists, building if necessary
          command: |
            source scm/utils-engage.sh; EnsurePyLibsImage
      - run:
          name: Ensure RpApp Image Exists, building if necessary
          command: |
            source scm/utils-engage.sh; EnsureRpAppImage
      - run:
          name: Figure out tag to use
          command: |
            BRANCH=${CIRCLE_BRANCH#*/}
            VERSION_STR=$(cat VERSION)
            if [[ ! -z $CIRCLE_TAG ]]; then
              VERSION_TAG="${VERSION_STR}"
            elif [[ "$BRANCH" == "develop" ]]; then
              VERSION_TAG="${VERSION_STR}-dev"
            else
              VERSION_TAG="ci-${VERSION_STR}-${BRANCH}"
            fi
            echo ${VERSION_TAG} > scm/version_tag.txt
      - run:
          name: Build "Default Branding" Image
          command: |
            VERSION_TAG=$(cat scm/version_tag.txt)
            source scm/utils-engage.sh; BuildVersionForRp "$VERSION_TAG"
      - run:
          name: Build "Engage Branding" Image
          command: |
            BRANCH=${CIRCLE_BRANCH#*/}
            VERSION_TAG=$(cat scm/version_tag.txt)
            source scm/utils-engage.sh; BuildVersionForEngage "$VERSION_TAG"
            if [[ $BRANCH == develop ]]; then
              IMAGE_NAME=istresearch/p4-engage
              IMAGE_TAG=ci-develop
              docker tag ${IMAGE_NAME}:${$VERSION_TAG} ${IMAGE_NAME}:${IMAGE_TAG}
              docker push ${IMAGE_NAME}:${IMAGE_TAG}
            fi
      - run:
          name: Build "Generic Branding" Image
          command: |
            VERSION_TAG=$(cat scm/version_tag.txt)
            source scm/utils-engage.sh; BuildVersionForGeneric "${VERSION_TAG}-generic"
      - run:
          name: Deploy
          command: |
            BRANCH=${CIRCLE_BRANCH#*/}
            if [[ "$BRANCH" == "develop" ]] || [[ "$BRANCH" == "main" ]] || [[ "$BRANCH" == "master" ]]; then
              curl --user ${CIRCLE_API_USER_TOKEN}: --data build_parameters[CIRCLE_JOB]=eks_deploy --data build_parameters[DEPLOY_PROJECT]=pulse-engage https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/p4-deploy/tree/develop
            else
              echo "Skipping deploy step"
            fi

workflows:
  version: 2
  pipeline:
    jobs:
      - build-containers:
          context: globalconfig
          filters:
            tags:
              ignore: /^test-.*/
