version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build 
          command: |
            apk add --update python openssh git curl
            BRANCH=${CIRCLE_BRANCH#*/}
            VERSION=`cat VERSION`
            FROM_RP_TAG=v5.0.0
            if [[ ! -z $CIRCLE_TAG ]]; then
              VERSION_TAG="${VERSION}"
            elif [[ $BRANCH == develop ]]; then
              VERSION_TAG="${VERSION}-dev"
            else
              VERSION_TAG="ci-${VERSION}-${BRANCH}"
            fi
            docker build -t istresearch/p4-engage:code-${VERSION_TAG} .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push istresearch/p4-engage:code-${VERSION_TAG}
  package:
    docker:
      - image: spotify/alpine
    steps:
      - run:
          name: Trigger the docker build job
          command: |
            printf "Triggering a $TRIGGER_PROJECT build on the $TRIGGER_PROJECT_BRANCH branch\n\n"

            curl -XPOST --header "Content-Type: application/json" -d '{"'"branch"'":"'"$TRIGGER_PROJECT_BRANCH"'"}' https://circleci.com/api/v1.1/project/github/$ORGANIZATION/$TRIGGER_PROJECT/build?circle-token=$CIRCLE_TOKEN

            printf "\n\nBuild triggered\n\n"
            printf "Follow the progress of the build on \nhttps://circleci.com/gh/$ORGANIZATION/$TRIGGER_PROJECT/tree/$TRIGGER_PROJECT_BRANCH"
workflows:
  version: 2
  engage:
    jobs:
      - build:
          context: globalconfig
          filters:
            tags:
              ignore: /^test-.*/
      - package:
          requires:
            - build
          context: globalconfig
          filters:
            tags:
              ignore: /^test-.*/
