version: 2

jobs:
  build-containers:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run:
          name: Avoid "Are you sure you want to connect?" to GitHub
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            chmod 600 ~/.ssh/known_hosts
      - setup_remote_docker
      - run:
          name: Login to Docker
          command: |
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      - run:
          name: Source build scripts
          command: |
            export FROM_RP_TAG=v5.0.0
            export IMAGE_NAME=istresearch/p4-engage
            export BRANCH=${CIRCLE_BRANCH#*/}
            export VERSION_STR=$(cat VERSION)
            if [[ ! -z $CIRCLE_TAG ]]; then
              export VERSION_TAG="${VERSION_STR}"
            elif [[ "$BRANCH" == "develop" ]]; then
              export VERSION_TAG="${VERSION_STR}-dev"
            else
              export VERSION_TAG="ci-${VERSION_STR}-${BRANCH}"
            fi
      - run:
          name: Ensure Base GEOS Image Exists, building if necessary
          command: |
            source scm/utils-engage.sh; EnsureGeosImage ${IMAGE_NAME}
      - run:
          name: Ensure Libs Image Exists, building if necessary
          command: |
            source scm/utils-engage.sh; EnsureLibsImage ${IMAGE_NAME}
      - run:
          name: Build Engage Code Image
          command: |
            IMAGE_TAG=code-${VERSION_TAG}
            UILIBS_TAG=$(cat scm/uilibs_tag.txt)
            echo "Building Docker container $IMAGE_NAME:$IMAGE_TAG using :${UILIBS_TAG}..."
            docker build --build-arg FROM_UILIBS_TAG=${UILIBS_TAG} -t $IMAGE_NAME:$IMAGE_TAG -f docker/Dockerfile.code .
            docker push $IMAGE_NAME:$IMAGE_TAG
            scm/pr-comment.sh "Container built: $IMAGE_NAME:$IMAGE_TAG"
      - run:
          name: Build "Default Branding" Image
          command: |
            IMG_NAME=istresearch/rapidpro
            IMG_TAG=${VERSION_TAG}
            echo "Building Docker container ${IMG_NAME}:${IMG_TAG}..."
            docker build --build-arg VERSION_TAG=$VERSION_TAG -t ${IMG_NAME}:${IMG_TAG} -f docker/Dockerfile.rp .
            docker push ${IMG_NAME}:${IMG_TAG}
            scm/pr-comment.sh "Container built: ${IMG_NAME}:${IMG_TAG}"
      - run:
          name: Build "Engage Branding" Image
          command: |
            IMG_NAME=istresearch/p4-engage
            IMG_TAG=${VERSION_TAG}
            echo "Building Docker container ${IMG_NAME}:${IMG_TAG}..."
            docker build --build-arg VERSION_TAG=$VERSION_TAG -t ${IMG_NAME}:${IMG_TAG} -f docker/Dockerfile.engage .
            docker push ${IMG_NAME}:${IMG_TAG}
            scm/pr-comment.sh "Container built: ${IMG_NAME}:${IMG_TAG}"
            if [[ $BRANCH == develop ]]; then
              docker tag ${IMG_NAME}:${IMG_TAG} ${IMG_NAME}:ci-develop
              docker push ${IMG_NAME}:ci-develop
            fi
      - run:
          name: Build "Generic Branding" Image
          command: |
            IMG_NAME=istresearch/rapidpro
            IMG_TAG=${VERSION_TAG}-generic
            echo "Building Docker container ${IMG_NAME}:${IMG_TAG}..."
            docker build --build-arg VERSION_TAG=$VERSION_TAG -t ${IMG_NAME}:${IMG_TAG} -f docker/Dockerfile.generic .
            docker push ${IMG_NAME}:${IMG_TAG}
            scm/pr-comment.sh "Container built: ${IMG_NAME}:${IMG_TAG}"
      - run:
          name: Deploy
          command: |
            if [[ "$BRANCH" == "develop" ]] || [[ "$BRANCH" == "main" ]] || [[ "$BRANCH" == "master" ]]; then
              curl --user ${CIRCLE_API_USER_TOKEN}: --data build_parameters[CIRCLE_JOB]=eks_deploy --data build_parameters[DEPLOY_PROJECT]=pulse-engage https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/p4-deploy/tree/develop
            else
              echo "Skipping deploy step"
            fi

workflows:
  version: 2
  pipeline:
    jobs:
      - build-containers:
          context: globalconfig
          filters:
            tags:
              ignore: /^test-.*/
