version: 2

jobs:
  build-stage-base:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run:
          name: Pre-build Setup
          command: |
            mkdir -p workspace/info
            source scm/utils.sh; EnsureGitHubIsKnownHost
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
      - run:
          name: Ensure Base Image Exists
          command: |
            source scm/utils-engage.sh; EnsureBaseImageExists;
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory.
          # This directory is considered to be the root directory of the workspace.
          root: workspace
          # Must be relative path from root
          paths:
            - info
  build-stage-pylibs:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: 2xlarge
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: workspace
      - run:
          name: Pre-build Setup
          command: |
            source scm/utils.sh; EnsureGitHubIsKnownHost
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
      - run:
          name: Ensure Pylibs Image Exists
          no_output_timeout: 180m
          command: |
            source scm/utils-engage.sh; EnsurePyLibsImageExists;
      - persist_to_workspace:
          root: workspace
          paths:
            - info/pylibs_tag.txt
  build-stage-pylibs-amd64:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: workspace
      - run:
          name: Pre-build Setup
          command: |
            source scm/utils.sh; EnsureGitHubIsKnownHost
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
      - run:
          name: Ensure Pylibs-amd64 Image Exists
          command: |
            source scm/utils-engage.sh; EnsurePyLibsImageExists "amd64";
      - persist_to_workspace:
          root: workspace
          paths:
            - info/pylibs-amd64_tag.txt
  build-stage-pylibs-arm64:
    machine:
      image: arm-default
    resource_class: arm.medium
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: workspace
      - run:
          name: Pre-build Setup
          command: |
            source scm/utils.sh; EnsureGitHubIsKnownHost
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
      - run:
          name: Ensure Pylibs-arm64 Image Exists
          command: |
            source scm/utils-engage.sh; EnsurePyLibsImageExists "arm64";
      - persist_to_workspace:
          root: workspace
          paths:
            - info/pylibs-arm64_tag.txt
  build-stage-pylibs-manifest:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: workspace
      - run:
          name: Pre-build Setup
          command: |
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
      - run:
          name: Ensure Pylibs Image Exists
          command: |
            IMG1_TAG=$(cat "${WORKSPACE}/info/pylibs-amd64_tag.txt")
            IMG2_TAG=$(cat "${WORKSPACE}/info/pylibs-arm64_tag.txt")
            STAGE_HASH="${IMG1_TAG##*-}"
            IMG_NAME=istresearch/p4-engage
            IMG_TAG="pylibs-${STAGE_HASH}"
            echo "${IMG_TAG}" > "${WORKSPACE}/info/pylibs_tag.txt"
            docker manifest create "${IMG_NAME}:${IMG_TAG}" \
              --amend "istresearch/p4-engage:${IMG1_TAG}" \
              --amend "istresearch/p4-engage:${IMG2_TAG}"
            docker manifest push "${IMG_NAME}:${IMG_TAG}"
      - persist_to_workspace:
          root: workspace
          paths:
            - info/pylibs_tag.txt
  build-stage-pyapp:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install Docker Buildx for Multi-Architectures
          command: |
            source scm/utils.sh; multiArch_installBuildx;
            source scm/utils.sh; multiArch_addArm64Arch;
            source scm/utils.sh; multiArch_createBuilderContext;
      - run:
          name: Pre-build Setup
          command: |
            source scm/utils.sh; EnsureGitHubIsKnownHost
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
      - run:
          name: Figure out tag to use
          command: |
            source scm/utils-engage.sh; EnsureAppImageTagExists;
      - run:
          name: Ensure PyApp Image Exists, building if necessary
          no_output_timeout: 180m
          command: |
            source scm/utils-engage.sh; EnsurePyAppImageExists;
  build-stage-engage:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install Docker Buildx for Multi-Architectures
          command: |
            source scm/utils.sh; multiArch_installBuildx;
            source scm/utils.sh; multiArch_addArm64Arch;
            source scm/utils.sh; multiArch_createBuilderContext;
      - run:
          name: Pre-build Setup
          command: |
            source scm/utils.sh; EnsureGitHubIsKnownHost
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
      - run:
          name: Figure out tag to use
          command: |
            source scm/utils-engage.sh; EnsureAppImageTagExists;
      - run:
          name: Build Engage Brand Image
          command: |
            source scm/utils-engage.sh; BuildVersionForEngage "$(cat "${WORKSPACE}/info/version_tag.txt")"
  build-stage-generic:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install Docker Buildx for Multi-Architectures
          command: |
            source scm/utils.sh; multiArch_installBuildx;
            source scm/utils.sh; multiArch_addArm64Arch;
            source scm/utils.sh; multiArch_createBuilderContext;
      - run:
          name: Pre-build Setup
          command: |
            source scm/utils.sh; EnsureGitHubIsKnownHost
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
      - run:
          name: Figure out tag to use
          command: |
            source scm/utils-engage.sh; EnsureAppImageTagExists;
      - run:
          name: Build Engage Brand Image
          command: |
            source scm/utils-engage.sh; BuildVersionForGeneric "$(cat "${WORKSPACE}/info/version_tag.txt")-generic"
  build-stage-rp:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install Docker Buildx for Multi-Architectures
          command: |
            source scm/utils.sh; multiArch_installBuildx;
            source scm/utils.sh; multiArch_addArm64Arch;
            source scm/utils.sh; multiArch_createBuilderContext;
      - run:
          name: Pre-build Setup
          command: |
            source scm/utils.sh; EnsureGitHubIsKnownHost
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
      - run:
          name: Figure out tag to use
          command: |
            source scm/utils-engage.sh; EnsureAppImageTagExists;
      - run:
          name: Build Engage Brand Image
          command: |
            source scm/utils-engage.sh; BuildVersionForRp "$(cat "${WORKSPACE}/info/version_tag.txt")"
  build-multi-arch-containers:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install Docker Buildx for Multi-Architectures
          command: |
            source scm/utils.sh; multiArch_installBuildx;
            source scm/utils.sh; multiArch_addArm64Arch;
            source scm/utils.sh; multiArch_createBuilderContext;
      - run:
          name: Pre-build Setup
          command: |
            source scm/utils.sh; EnsureGitHubIsKnownHost
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
      - run:
          name: Ensure GEOS Libs Image Exists, building if necessary
          command: |
            source scm/utils-engage.sh; EnsureGeosImage default mabuild;
      - run:
          name: Ensure Python Libs Image Exists, building if necessary
          command: |
            source scm/utils-engage.sh; EnsurePyLibsImage default mabuild;
      - run:
          name: Figure out tag to use
          command: |
            source scm/utils-engage.sh; determine_image_tag;
            VERSION_TAG=$(cat scm/version_tag.txt);
            echo "Using tag: ${VERSION_TAG}";
      - run:
          name: Ensure PyApp Image Exists, building if necessary
          command: |
            source scm/utils-engage.sh; EnsurePyAppImage default mabuild;
      - run:
          name: Build "Default Branding" Image
          command: |
            VERSION_TAG=$(cat scm/version_tag.txt)
            source scm/utils-engage.sh; BuildVersionForRp "$VERSION_TAG" mabuild
      - run:
          name: Build "Engage Branding" Image
          command: |
            VERSION_TAG=$(cat scm/version_tag.txt)
            source scm/utils-engage.sh; BuildVersionForEngage "$VERSION_TAG" mabuild
      - run:
          name: Build "Generic Branding" Image
          command: |
            VERSION_TAG=$(cat scm/version_tag.txt)
            source scm/utils-engage.sh; BuildVersionForGeneric "${VERSION_TAG}-generic" mabuild

  build-containers:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Avoid "Are you sure you want to connect?" to GitHub
          command: |
            mkdir -p ~/.ssh;
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts;
            chmod 600 ~/.ssh/known_hosts;
      - setup_remote_docker:
          version: 20.10.7
          # Base GEOS image cannot build, force ver 20.10.7: https://discuss.circleci.com/t/unable-to-use-make/40552/4
      - run:
          name: Login to Docker
          command: |
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
      - run:
          name: Ensure GEOS Libs Image Exists, building if necessary
          command: |
            source scm/utils-engage.sh; EnsureGeosImage;
      - run:
          name: Ensure Python Libs Image Exists, building if necessary
          command: |
            source scm/utils-engage.sh; EnsurePyLibsImage;
      - run:
          name: Figure out tag to use
          command: |
            source scm/utils-engage.sh; determine_image_tag;
            VERSION_TAG=$(cat scm/version_tag.txt);
            echo "Using tag: ${VERSION_TAG}";
      - run:
          name: Ensure PyApp Image Exists, building if necessary
          command: |
            VERSION_TAG=$(cat scm/version_tag.txt)
            source scm/utils-engage.sh; EnsurePyAppImage default "$VERSION_TAG"
      - run:
          name: Build "Default Branding" Image
          command: |
            VERSION_TAG=$(cat scm/version_tag.txt)
            # only build this if constructing a tag version
            if [[ ! -z $CIRCLE_TAG ]]; then
              source scm/utils-engage.sh; BuildVersionForRp "$VERSION_TAG"
            fi
      - run:
          name: Build "Engage Branding" Image
          command: |
            BRANCH=${CIRCLE_BRANCH#*/}
            VERSION_TAG=$(cat scm/version_tag.txt)
            source scm/utils-engage.sh; BuildVersionForEngage "$VERSION_TAG"
            if [[ $BRANCH == develop ]]; then
              IMAGE_NAME=istresearch/p4-engage
              IMAGE_TAG=ci-develop
              docker tag ${IMAGE_NAME}:${VERSION_TAG} ${IMAGE_NAME}:${IMAGE_TAG}
              docker push ${IMAGE_NAME}:${IMAGE_TAG}
            fi
      - run:
          name: Build "Generic Branding" Image
          command: |
            VERSION_TAG=$(cat scm/version_tag.txt)
            source scm/utils-engage.sh; BuildVersionForGeneric "${VERSION_TAG}-generic"

  deploy-dev-container:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Avoid "Are you sure you want to connect?" to GitHub
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            chmod 600 ~/.ssh/known_hosts
      - run:
          name: Figure out tag to use
          command: |
            BRANCH=${CIRCLE_BRANCH#*/}
            VERSION_STR=$(cat VERSION)
            if [[ -n $CIRCLE_TAG ]]; then
              VERSION_TAG="${CIRCLE_TAG#*v}"
            elif [[ "$BRANCH" == "develop" ]]; then
              VERSION_TAG="${VERSION_STR}-dev"
            elif [[ "$BRANCH" != "master" ]]; then
              VERSION_TAG="ci-${VERSION_STR}-${BRANCH}"
            fi
            echo ${VERSION_TAG} > scm/version_tag.txt
            echo "Using tag: ${VERSION_TAG}"
      - run:
          name: Deploy To K8s
          command: |
            VERSION_TAG=$(cat scm/version_tag.txt)
            K8_URL=https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/p4-deploy/tree/develop
            echo "Deploy to K8s: $CIRCLE_PROJECT_USERNAME/p4-engage:${VERSION_TAG}"
            curl -XPOST --user "${oCI_API_TOKEN}:" \
              --data build_parameters[CIRCLE_JOB]=eks_deploy \
              --data build_parameters[DEPLOY_PROJECT]=pulse-engage \
              --data build_parameters[DEPLOY_IMAGE]=$CIRCLE_PROJECT_USERNAME/p4-engage:${VERSION_TAG} \
              $K8_URL

workflows:
  version: 2
  build-docker-images:
    jobs:
      - build-stage-base:
          context: globalconfig
      - build-stage-pylibs-amd64:
          context: globalconfig
          requires:
            - build-stage-base
      - build-stage-pylibs-arm64:
          context: globalconfig
          requires:
            - build-stage-base
      - build-stage-pylibs-manifest:
          context: globalconfig
          requires:
            - build-stage-pylibs-amd64
            - build-stage-pylibs-arm64
      - build-stage-pyapp:
          context: globalconfig
          requires:
            - build-stage-pylibs-manifest
          filters: &ma-filters
            branches:
              only:
                - /^ma\/.*/
            tags:
              only:
                - /^v.*/
                - /^ma[-\/].*/
      - build-stage-engage:
          context: globalconfig
          requires:
            - build-stage-pyapp
          filters: *ma-filters
      - build-stage-generic:
          context: globalconfig
          requires:
            - build-stage-pyapp
          filters: *ma-filters
      - build-stage-rp:
          context: globalconfig
          requires:
            - build-stage-pyapp
          filters: *ma-filters
      - build-multi-arch-containers:
          context: globalconfig
          filters:
            branches:
              only:
                - /^none$/
      - build-containers:
          context: globalconfig
          filters:
            branches:
              ignore:
                - /^rel\/.*/
                - /^master$/
                - /^main$/
                - /^ma\/.*/
            tags:
              ignore:
                - /^test-.*/
                - /^v.*/
                - /^ma[-\/].*/
      - deploy-dev-container:
          context: globalconfig
          requires:
            - build-containers
          filters:
            branches:
              only:
                - /^develop$/
                - /^dev[-\/].*/
