# Generated by Django 2.2.4 on 2020-03-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0121_auto_20191112_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='last_sync',
            field=models.ForeignKey(blank=True, help_text='The last time that this channel was synced to the device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='channels.SyncEvent', verbose_name='Last Sync'),
        ),
        migrations.AlterField(
            model_name='syncevent',
            name='channel',
            field=models.ForeignKey(help_text='The channel that synced to the server', on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='channels.Channel', verbose_name='Channel'),
        ),
    ]
