# Generated by Django 2.2.4 on 2020-04-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0122_auto_20200323_2134'),
        ('channels', '0122_populate_allow_international'),
    ]

    operations = [
    ]
