# Generated by Django 2.2.4 on 2022-01-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0126_auto_20210105_1444'),
        ('channels', '0123_auto_20201026_1945'),
    ]

    operations = [
    ]
