# Generated by Django 4.0.4 on 2022-05-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0136_alter_alert_created_by_alter_alert_modified_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
    ]
