# Generated by Django 2.2.4 on 2020-07-01 17:56

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0139_auto_20200511_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='text',
            field=temba.utils.models.TranslatableField(help_text='The localized versions of the message text', max_length=640, verbose_name='Translations'),
        ),
    ]
