# Generated by Django 2.2.4 on 2022-01-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0153_auto_20210712_1723'),
        ('msgs', '0140_auto_20200701_1756'),
    ]

    operations = [
    ]
