# Generated by Django 2.2.10 on 2021-01-26 18:34

from django.db import migrations, models


# EDIT:
# did not have 0002 at all during last merge, trying to avoid:
# InconsistentMigrationHistory: Migration flows.0247_auto_20210126_1834 is applied before its dependency sql.0002_updates
class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0246_auto_20210119_1717"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowpathrecentrun", name="id", field=models.BigAutoField(primary_key=True, serialize=False)
        ),
    ]
