ARG FROM_BASE_TAG
FROM alpine as load-files

COPY docker/geolibs.sh /opt/

# ========================================================================

FROM istresearch/p4-engage:${FROM_BASE_TAG} as base-stage

COPY --from=load-files /opt /

RUN set -ex \
 && apk add --no-cache --virtual .build-deps \
	  gcc \
	  g++ \
	  make \
	  libc-dev \
	  musl-dev \
	  linux-headers \
 && sh /geolibs.sh \
 && apk del .build-deps \
 && rm /geolibs.sh
