# Generated by Django 2.2.20 on 2021-06-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifiers", "0002_auto_20191111_1942"),
        ("orgs", "0071_orgactivity_plan_active_contact_count"),
        ("channels", "0123_auto_20201026_1945"),
        ("airtime", "0014_auto_20191023_1904"),
        ("tickets", "0003_auto_20200602_1522"),
        ("request_logs", "0007_auto_20200526_1931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="url",
            field=models.URLField(max_length=2048),
        ),
    ]
