# Generated by Django 2.1.8 on 2019-07-01 22:25

from django.db import migrations

from . import InstallSQL


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0001_initial"),
    ]

    operations = [
        InstallSQL("0002_functions"),
        InstallSQL("0002_indexes"),
        InstallSQL("0002_triggers"),
    ]
