# Generated by Django 4.0.3 on 2022-03-31 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("triggers", "0022_alter_trigger_created_by_alter_trigger_modified_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trigger",
            options={"verbose_name": "Trigger", "verbose_name_plural": "Triggers"},
        ),
    ]
