name: "Build (1 of 6) Base OS Layer"

on:
  push:
    branches-ignore:
      - main
      - master
    tags:
      - 'v*'

jobs:
  build_cfg:
    runs-on: ubuntu-latest
    environment: default
    env:
      REF_NAME: ${{ github.ref_name }}
    outputs:
      VERSION_STR: ${{ steps.config_step.outputs.VERSION_STR }}
      VERSION_INT: ${{ steps.config_step.outputs.VERSION_INT }}
      VERSION_KIND: ${{ steps.config_step.outputs.VERSION_KIND }}
      ALT_TAGS: ${{ steps.config_step.outputs.ALT_TAGS }}
    steps:
      - name: "Determine Tag To Use"
        id: config_step
        run: |-
          #VER_KIND = 'alpha' (not deployed) | 'dev' | 'beta' | 'gold'
          if [[ "${REF_NAME%/**}" == "dev" || "${REF_NAME}" == "develop" ]]; then
            VER_KIND=dev
          else
            VER_KIND=alpha
          fi
          
          VER_BUILD=$(date +%H%M)
          # limit to only first 3 chars
          VER_BUILD=${VER_BUILD:0:3}
          # recreate as INT, leaving 0's in place; creates a 'reasonable' 32-bit signed int.
          VERSION_INT="$(date +%y)$(date +%m)$(date +%d)${VER_BUILD}"

          ALT_TAGS=""
          if [[ ${{ github.ref_name }} =~ ^(v)([[:digit:]]+\..*)$ ]]; then
            VER_KIND=gold
            VERSION_STR=${BASH_REMATCH[2]}
          else          
            # 'strict' semver segments cannot start with 0
            VERSION_NUM="$(date +%y).$(date +%-m).$(date +%-d).${VER_BUILD#0}"  
            VERSION_STR=ci-${VERSION_NUM}
            if [[ "${REF_NAME}" == "develop" ]]; then
              ALT_TAGS+=",ci-develop"
            else
              ALT_TAGS=",ci-dev-${REF_NAME#**/}"
            fi
          fi
          echo "VERSION_INT=${VERSION_INT}" >> $GITHUB_OUTPUT
          echo "VERSION_STR=${VERSION_STR}" >> $GITHUB_OUTPUT
          echo "VERSION_KIND=${VER_KIND}" >> $GITHUB_OUTPUT
          echo "ALT_TAGS=${ALT_TAGS}" >> $GITHUB_OUTPUT

          echo "::notice::Version KIND=${VER_KIND}, STR=${VERSION_STR}${ALT_TAGS}, INT=${VERSION_INT}"
  #endjob build_cfg

  build_image:
    needs: [build_cfg]
    uses: ./.github/workflows/util-build-img1-os-layer.yml
    secrets: inherit
    with:
      repo_ref_type: ${{ github.ref_type }}
      repo_ref_name: ${{ github.ref_name }}
      version_str: ${{ needs.build_cfg.outputs.VERSION_STR }}
      version_int: ${{ needs.build_cfg.outputs.VERSION_INT }}
      version_kind: ${{ needs.build_cfg.outputs.VERSION_KIND }}
      alt_tags: ${{ needs.build_cfg.outputs.ALT_TAGS }}
  #endjob build_image
