name: "Build (5 of 6) Generic Brand"

on:
  repository_dispatch:
    types: [build_layer_generic, build_layer_generic_files_error]

jobs:
  build_result:
    name: "Build Generic Files Layer Result [#${{ github.event.client_payload.run_number }}]"
    runs-on: ubuntu-latest
    env:
      RUN_URL: "[Run #${{ github.event.client_payload.run_number }}](${{ github.event.client_payload.run_url }})"
    steps:
      - name: "Display Error Msg"
        if: github.event.client_payload.error_msg != ''
        run: |-
          echo -e "::error::${RUN_URL}%0A${{ github.event.client_payload.error_msg }}"
          exit 1
      - name: "Display Success Msg"
        if: github.event.client_payload.build_msg != ''
        run: |-
          echo -e "::notice::${RUN_URL}%0A${{ github.event.client_payload.build_msg }}"
  #endjob build_result

  build_cfg:
    needs: [build_result]
    runs-on: ubuntu-latest
    environment: default
    env:
      ALT_TAG: ${{ github.event.client_payload.version.alt }}
    outputs:
      DOCKERFILE2USE: "docker/final-generic.dockerfile"
      IMAGE_NAME: "${{ github.repository_owner }}/rapidpro"
      IMAGE_TAG: "${{ github.event.client_payload.version.str }}-generic"
      ALT_TAG: ${{ steps.config_step.outputs.ALT_TAG }}
      BUILD_FLAG: ${{ steps.config_step.outputs.BUILD_FLAG }}
    steps:
      - name: "Config For Generic Build"
        id: config_step
        env:
          REF_NAME: "${{ github.event.client_payload.repo.ref_name }}"
        run: |-
          if [[ -n "${{ github.event.client_payload.version.alt }}" ]]; then
            ALT_TAG=",${ALT_TAG#,}-generic"
            echo "ALT_TAG=${ALT_TAG}" >> GITHUB_OUTPUT
          fi
          if [[ "${{ github.event.client_payload.version.kind }}" == "gold" ]]; then
            BUILD_FLAG=1
          else
            # setting to 1 here, too, as logic moved to img4-generic; if this is called, just build.
            BUILD_FLAG=1
          fi
          echo "BUILD_FLAG=${BUILD_FLAG}" >> $GITHUB_OUTPUT
  #endjob build_cfg

  trigger-build:
    if: needs.build_cfg.outputs.BUILD_FLAG == 1
    runs-on: ubuntu-latest
    needs: [build_cfg]
    environment: default
    steps:
      - name: "Trigger Container Build"
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CI_WEBHOOK_TOKEN }}
          repository: istresearch/ci-docker
          event-type: build-repo
          client-payload: |-
            {
              "repo": {
                "name": "${{ github.repository }}",
                "ref_type": "${{ github.event.client_payload.repo.ref_type }}",
                "ref_name": "${{ github.event.client_payload.repo.ref_name }}"
              },
              "image": {
                "dockerfile": "${{ needs.build_cfg.outputs.DOCKERFILE2USE }}",
                "arch_allowed": "${{ github.event.client_payload.image.arch_allowed }}",
                "name": "${{ needs.build_cfg.outputs.IMAGE_NAME }}",
                "tag": "${{ needs.build_cfg.outputs.IMAGE_TAG }}${{ needs.build_cfg.outputs.ALT_TAG }}",
                "build_args": [
                  "FROM_STAGE=${{ github.event.client_payload.image.layer }}",
                  "STATICFILES_FROM_IMAGE=${{ github.event.client_payload.image.pyfiles }}",
                  "VERSION_CI=${{ github.event.client_payload.version.int }}",
                  "VERSION_TAG=${{ github.event.client_payload.version.str }}"
                ]
              },
              "deployment": {
                "deploy_flag": "0"
              },
              "callback": {
                "repository": "${{ github.repository }}",
                "event_type": "build_nginx",
                "error_type": "build_generic_error",
                "payload": {
                  "repo": {
                    "ref_type": "${{ github.event.client_payload.repo.ref_type }}",
                    "ref_name": "${{ github.event.client_payload.repo.ref_name }}"
                  },
                  "image": {
                    "name": "${{ needs.build_cfg.outputs.IMAGE_NAME }}",
                    "arch_allowed": "${{ github.event.client_payload.image.arch_allowed }}",
                    "layer": "${{ needs.build_cfg.outputs.IMAGE_NAME }}:${{ needs.build_cfg.outputs.IMAGE_TAG }}"
                  },
                  "version": {
                    "str": "${{ github.event.client_payload.version.str }}",
                    "int": "${{ github.event.client_payload.version.int }}",
                    "kind": "${{ github.event.client_payload.version.kind }}",
                    "alt": "${{ github.event.client_payload.version.alt }}"
                  },
                  "deploy": 0
                }
              }
            }
  #endjob trigger-build
