name: "Display Build Conclusions"

on:
  repository_dispatch:
    types:
      - build_layer4_generic
      - build_layer4_generic_error
      - build_layer4_rp
      - build_layer4_rp_error
      - build_layer5_error

jobs:
  layer4_success:
    if: github.event.client_payload.error_msg == ''
    name: "Display Msg [${{ github.event.action }}]"
    runs-on: ubuntu-latest
    steps:
      - run: |-
          echo -e "::notice::${{ github.event.client_payload.name }} image built with tag [${{ github.event.client_payload.tag }}]"
  #endjob layer4_success

  layer4or5_error:
    if: github.event.client_payload.error_msg != ''
    name: "Run [${{ github.event.client_payload.run_id }}] Failed for [${{ github.event.action }}]"
    runs-on: ubuntu-latest
    steps:
      - run: |-
          echo -e "::error::${{ github.event.client_payload.error_msg }}"
          exit 1
  #endjob layer4or5_error
