name: "Display Build Conclusions"

on:
  repository_dispatch:
    types:
      - build_layer4_engage
      - build_layer4_generic
      - build_layer4_rp
      - build_layer4_error

jobs:
  layer4_success:
    if: github.event.client_payload.error_msg == ''
    runs-on: ubuntu-latest
    steps:
      - name: "Display Msg"
        run: |-
          echo "::notice::${{ github.event.client_payload.name }} image built with tag [${{ github.event.client_payload.tag }}]"
  #endjob layer4_success

  layer4_error:
    if: github.event.client_payload.error_msg != ''
    runs-on: ubuntu-latest
    steps:
      - name: "Display Err Msg"
        run: |-
          echo "::error::${{ github.event.client_payload.error_msg }}"
          exit 1
  #endjob layer4_error
