name: "Build Nginx w/static files"

on:
  repository_dispatch:
    types:
      - build_layer5
      - build_layer4_engage_error

env:
  VERSION_STR: ${{ github.event.client_payload.image.tag }}
  VER_NUM: ${{ github.event.client_payload.image.ver_num }}
  FROM_LAYER: ${{ github.event.client_payload.image.layer4 }}
  FROM_LAYER_TAG: ${{ github.event.client_payload.image.layer4tag }}

jobs:
  build_result:
    name: "Build Layer 4 Result [#${{ github.event.client_payload.run_number }}]"
    runs-on: ubuntu-latest
    env:
      RUN_URL: "[Run #${{ github.event.client_payload.run_number }}](${{ github.event.client_payload.run_url }})"
    steps:
      - name: "Display Error Msg"
        if: github.event.client_payload.error_msg != ''
        run: |-
          echo -e "::error::${RUN_URL}%0A${{ github.event.client_payload.error_msg }}"
          exit 1
      - name: "Display Success Msg"
        if: github.event.client_payload.build_msg != ''
        run: |-
          echo -e "::notice::${RUN_URL}%0A${{ github.event.client_payload.build_msg }}"
  #endjob build_result

  build_cfg:
    needs: [build_result]
    runs-on: ubuntu-latest
    environment: default
    outputs:
      DOCKERFILE2USE: ${{ steps.config_step.outputs.DOCKERFILE2USE }}
      IMAGE_NAME: ${{ steps.config_step.outputs.IMAGE_NAME }}
      IMAGE_TAG: ${{ steps.config_step.outputs.IMAGE_TAG }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.repo.ref_name }}

      - name: "Config For Nginx Build"
        id: config_step
        run: |-
          DOCKERFILE2USE="docker/nginx/nginx.dockerfile"
          echo "DOCKERFILE2USE=${DOCKERFILE2USE}" >> $GITHUB_OUTPUT

          IMAGE_NAME=${{ github.repository_owner }}/p4-engage
          IMAGE_TAG=nginx-${VERSION_STR}
          echo "::notice::Build: ${IMAGE_NAME}:${IMAGE_TAG}"
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
  #endjob build_cfg

  trigger-build:
    runs-on: ubuntu-latest
    needs: [build_cfg]
    environment: default
    steps:
      - name: "Trigger Container Build For Nginx"
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CI_WEBHOOK_TOKEN }}
          repository: istresearch/ci-docker
          event-type: build-repo
          client-payload: |-
            {
              "repo": {
                "name": "${{ github.repository }}",
                "ref_type": "${{ github.event.client_payload.repo.ref_type }}",
                "ref_name": "${{ github.event.client_payload.repo.ref_name }}"
              },
              "image": {
                "dockerfile": "${{ needs.build_cfg.outputs.DOCKERFILE2USE }}",
                "arch_allowed": "amd64 arm64",
                "name": "${{ needs.build_cfg.outputs.IMAGE_NAME }}",
                "tag": "${{ needs.build_cfg.outputs.IMAGE_TAG }}",
                "build_args": [
                  "STATICFILES_FROM_IMAGE=${{ env.FROM_LAYER }}"
                ]
              },
              "deployment": {
                "deploy_flag": "${{ github.ref_type != 'branchXXXX' }}",
                "k8s": [ {
                  "project": "pulse-engage-nginx",
                  "container": "nginx",
                  "deploy_msg": ""
                } ]
              },
              "callback": {
                "repository": "${{ github.repository }}",
                "event_type": "build_nginx_success",
                "error_type": "build_nginx_error"
              }
            }
  #endjob trigger-build

  trigger-build-webstatic:
    if: github.event.client_payload.image.repo_filepath != ''
    needs: [build_result]
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: "Trigger Archive Build For Static Website Files"
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CI_WEBHOOK_TOKEN }}
          repository: istresearch/postoffice
          event-type: build-webstatic
          client-payload: |-
            {
              "repo": {
                "name": "${{ github.repository }}",
                "ref_type": "${{ github.event.client_payload.repo.ref_type }}",
                "ref_name": "${{ github.event.client_payload.repo.ref_name }}"
              },
              "data": {
                "image2use": "${{ env.FROM_LAYER }}",
                "repo_filepath": "${{ github.event.client_payload.image.repo_filepath }}"
              },
              "callback": {
                "repository": "${{ github.repository }}",
                "event_type": "build_webstatic_success",
                "error_type": "build_webstatic_error"
              }
            }
  #endjob trigger-build-webstatic
