name: build image layer2

on:
  repository_dispatch:
    types: build_layer2

env:
  IMAGE_STAGE: pylibs
  DOCKERFILE2USE: docker/dfstage-pylibs.dockerfile

jobs:
  build_cfg:
    runs-on: ubuntu-latest
    environment: default
    outputs:
      REPO_BRANCH: ${{ steps.config_step.outputs.REPO_BRANCH }}
      REPO_TAG: ${{ steps.config_step.outputs.REPO_TAG }}
      IMAGE_NAME: ${{ steps.config_step.outputs.IMAGE_NAME }}
      IMAGE_TAG: ${{ steps.config_step.outputs.IMAGE_TAG }}
    steps:
      - uses: actions/checkout@v3

      - name: "Determine Tag To Use"
        id: config_step
        run: |-
          IMAGE_NAME=${{ github.repository_owner }}/p4-engage
          echo "${{ inputs.name }}" > prev-image-tag.txt
          source scm/utils-engage.sh
          IMAGE_TAG_HASH=$(CalcFileArgsMD5 "${DOCKERFILE2USE}" "prev-image-tag.txt" "poetry.lock" "pyproject.toml" "package-lock.json" "package.json")
          IMAGE_TAG="${IMAGE_STAGE}-${IMAGE_TAG_HASH}"
          echo "::notice::Layer2: ${IMAGE_NAME}:${IMAGE_TAG}"
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          
          if [[ ${{ github.ref_type }} == 'tag' ]]; then
            REPO_BRANCH=
            REPO_TAG=${{ github.ref_name }}
          else
            REPO_BRANCH=${{ github.ref_name }}
            REPO_TAG=
          fi
          echo "::notice::Repo Branch=${REPO_BRANCH}"
          echo "REPO_BRANCH=${REPO_BRANCH}" >> $GITHUB_OUTPUT
          echo "::notice::Repo Tag=${REPO_TAG}"
          echo "REPO_TAG=${REPO_TAG}" >> $GITHUB_OUTPUT
  #endjob build_cfg

  check_image_exist:
    needs: [build_cfg]
    uses: istresearch/ci-docker/.github/workflows/util-docker-image-exists.yml@v1
    secrets: inherit
    with:
      name: ${{ needs.build_cfg.outputs.IMAGE_NAME }}
      tag: ${{ needs.build_cfg.outputs.IMAGE_TAG }}
  #endjob check_image_exist

  check_build_image:
    runs-on: ubuntu-latest
    needs: [check_image_exist]
    environment: default
    env:
      BUILD_ERR_MSG: ${{ needs.check_image_exist.outputs.err_msg }}
    outputs:
      BUILD_STAGE: ${{ steps.is_building.outputs.BUILD_STAGE }}
    steps:
      - name: Set BUILD_STAGE output
        id: is_building
        run: |-
          if [[ -n "${BUILD_ERR_MSG}" ]]; then
            echo "${BUILD_ERR_MSG}"
            exit 1
          fi
          if [[ ${{ needs.check_image_exist.outputs.exists }} == 0 ]]; then
            BUILD_STAGE=1
          else
            BUILD_STAGE=0
          fi
          echo "::notice::Build Stage?=${BUILD_STAGE}"
          echo "BUILD_STAGE=${BUILD_STAGE}" >> $GITHUB_OUTPUT
  #endjob check_build_image

  trigger-build:
    if: needs.check_build_image.outputs.BUILD_STAGE == 1
    runs-on: ubuntu-latest
    needs: [build_cfg, check_build_image]
    environment: default
    steps:
      - name: Trigger Container Build
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CI_WEBHOOK_TOKEN }}
          repository: istresearch/ci-docker
          event-type: build-repo
          client-payload: |-
            {
              "repo": {
                "name": "${{ github.repository }}",
                "branch": "${{ needs.build_cfg.outputs.REPO_BRANCH }}",
                "tag": "${{ needs.build_cfg.outputs.REPO_TAG }}"
              },
              "image": {
                "dockerfile": "${{ env.DOCKERFILE2USE }}",
                "name": "${{ needs.build_cfg.outputs.IMAGE_NAME }}",
                "tag": "${{ needs.build_cfg.outputs.IMAGE_TAG }}",
                "build_args": [
                ]
              }
            }
  #endjob trigger-build

  trigger-next-stage:
    if: needs.build_cfg.outputs.BUILD_STAGE == 0
    runs-on: ubuntu-20.04
    needs: [build_cfg, check_build_image]
    environment: default
    steps:
      - name: Trigger Next Stage
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: build-layer3
          client-payload: |-
            {
              "layer2": "${{ needs.build_cfg.outputs.IMAGE_TAG }}"
            }
  #endjob trigger-next-stage
